name: Build Windows & Linux executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m venv venv
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            .\\venv\\Scripts\\activate
          else
            source venv/bin/activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build mini_report executable
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller src/main.py --onefile --name mini_report \
              --add-data="src/firebase-admin-sdk.json;." \
              --hidden-import=openpyxl
          else
            pyinstaller src/main.py --onefile --name mini_report \
              --add-data=src/firebase-admin-sdk.json:.
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mini_report-${{ matrix.os }}
          path: dist/mini_report*
